// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB52j6WiObzZn2UNts-tpC-N5PXaXJGRbg',
    appId: '1:701182164804:web:6b296135392f95969ee111',
    messagingSenderId: '701182164804',
    projectId: 'medgo-pharmacy-website',
    authDomain: 'medgo-pharmacy-website.firebaseapp.com',
    databaseURL: 'https://medgo-pharmacy-website-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'medgo-pharmacy-website.firebasestorage.app',
    measurementId: 'G-S696V9L4WR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0-DW_dCPQJQkaesmaOIP1-5yJPLrbOmI',
    appId: '1:701182164804:android:8184ce038e9b437b9ee111',
    messagingSenderId: '701182164804',
    projectId: 'medgo-pharmacy-website',
    databaseURL: 'https://medgo-pharmacy-website-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'medgo-pharmacy-website.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjay1Ay98iEquAg6tozcNm6xQwu1PzMVE',
    appId: '1:701182164804:ios:044f4ca9d96b07fa9ee111',
    messagingSenderId: '701182164804',
    projectId: 'medgo-pharmacy-website',
    databaseURL: 'https://medgo-pharmacy-website-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'medgo-pharmacy-website.firebasestorage.app',
    iosClientId: '701182164804-gn5ulv2ani8rqldti8dcpdgb66rk7nk9.apps.googleusercontent.com',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjay1Ay98iEquAg6tozcNm6xQwu1PzMVE',
    appId: '1:701182164804:ios:044f4ca9d96b07fa9ee111',
    messagingSenderId: '701182164804',
    projectId: 'medgo-pharmacy-website',
    databaseURL: 'https://medgo-pharmacy-website-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'medgo-pharmacy-website.firebasestorage.app',
    iosClientId: '701182164804-gn5ulv2ani8rqldti8dcpdgb66rk7nk9.apps.googleusercontent.com',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB52j6WiObzZn2UNts-tpC-N5PXaXJGRbg',
    appId: '1:701182164804:web:a68a221e740964c09ee111',
    messagingSenderId: '701182164804',
    projectId: 'medgo-pharmacy-website',
    authDomain: 'medgo-pharmacy-website.firebaseapp.com',
    databaseURL: 'https://medgo-pharmacy-website-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'medgo-pharmacy-website.firebasestorage.app',
    measurementId: 'G-QCSK0T3JJX',
  );

}